name: Import Excel and Create PR

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      spreadsheetId:
        description: '엑셀 파일의 스프레드시트 ID'
        required: true

jobs:
  import-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install exceljs only
        run: npm install exceljs

      - name: Convert Excel to JSON using extract-xlsx
        run: node script/extract-xlsx.cjs import https://docs.google.com/spreadsheets/d/${{ github.event.inputs.spreadsheetId }}/export?format=xlsx

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'feat: import excel to json via extract-xlsx'
          title: 'Import Excel to JSON'
          body: '엑셀 파일을 JSON으로 변환하여 추가합니다. (extract-xlsx 사용)'
          branch: import-excel-${{ github.run_id }}
          base: master

      - name: Show git status and log
        run: |
          git status
          git log --oneline --graph --decorate --all

      - name: Check Remote
        run: |
          git remote -v
          git branch -a
