name: Import Excel and Create PR

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      spreadsheetId:
        description: '엑셀 파일의 스프레드시트 ID'
        required: true

jobs:
  import-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install exceljs only
        run: npm install exceljs

      - name: Install dependencies
        run: npm install -g tsx

      - name: Convert Excel to JSON using extract-xlsx
        run: node script/i18n/extract-xlsx.cjs import https://docs.google.com/spreadsheets/d/${{ github.event.inputs.spreadsheetId }}/export?format=xlsx

      - name: Run TypeScript script
        run: tsx script/i18n/generate-i18n-types.ts

      - name: Set branch name with timestamp
        run: echo "BRANCH_NAME=auto/i18n-update-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Create a new branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b $BRANCH_NAME

      - name: Commit changes
        run: |
          git add .
          git commit -m "자동 번역 동기화"

      - name: Push changes
        run: |
          git push origin $BRANCH_NAME

      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'PR 제목',
              body: 'PR 설명',
              head: process.env.BRANCH_NAME,  // PR을 생성할 브랜치
              base: 'master'  // 타겟 브랜치
            });
