name: Import Excel and Create PR

on:
  workflow_dispatch:
    inputs:
      spreadsheetId:
        description: '엑셀 파일의 스프레드시트 ID'
        required: true

jobs:
  import-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install exceljs only
        run: npm install exceljs

      - name: Convert Excel to JSON using extract-xlsx
        run: node script/extract-xlsx.cjs import https://docs.google.com/spreadsheets/d/${{ github.event.inputs.spreadsheetId }}/export?format=xlsx

      - name: Create new branch
        run: |
          BRANCH="import-excel-$(date +%s)"
          git checkout -b $BRANCH
          git add src/lib/i18n/locales/*.json
          git commit -m "feat: import excel to json via extract-xlsx" || echo "No changes to commit"
          git push origin $BRANCH
          echo "branch_name=$BRANCH" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.branch_name }}
          title: 'Import Excel to JSON'
          body: '엑셀 파일을 JSON으로 변환하여 추가합니다. (extract-xlsx 사용)'
